spring:
  application:
    name: ace-ui
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

    #热部署启动
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  http:
    encoding:
      charset: UTF-8


server:
  port: 8766

  tomcat:
    uri-encoding: UTF-8



